# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_base) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,1f,0f,-1.4986f,0.0654f,0f,4.4625f,-0.0654f,-1.4986f,0f,-0.284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_capsule_l2r0_125) {transformation: [-1.3333f,0f,0f,0f,0f,0.983f,-0.9008f,4.3242f,0f,-0.9008f,-0.983f,-0.1573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hand) {transformation: [-1f,0f,0f,0f,0f,0.7373f,-0.6756f,3.875f,0f,-0.6756f,-0.7373f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm4) {transformation: [-1.0417f,0f,0f,0f,0f,0f,-1.0417f,2.375f,0f,-1.0417f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_3) {transformation: [-1f,0f,0f,0f,0f,0f,-1f,2f,0f,-1f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_2) {transformation: [-1.1667f,0f,0f,0f,0f,1.1667f,0f,0.5f,0f,0f,-1.1667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cap_locator_1":{"px":1.9267516907609236e-17,"py":4.324231998782365,"pz":-0.15733121517995266,"ry":180,"rx":-47.50000000000002}}}