# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:blueprint/animations/animation_model_stand/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.animation_model_stand.frame 1