# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute if entity @s[tag=aj.blueprint.animation.animation_model_stand.playing] run function animated_java:blueprint/animations/animation_model_stand/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.animation_model_vslash.playing] run function animated_java:blueprint/animations/animation_model_vslash/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.animation_model_hslash.playing] run function animated_java:blueprint/animations/animation_model_hslash/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.animation_model_slash.playing] run function animated_java:blueprint/animations/animation_model_slash/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.animation_model_stab.playing] run function animated_java:blueprint/animations/animation_model_stab/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:blueprint/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~