# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.animation_model_hslash.frame matches 61.. run scoreboard players set @s aj.animation_model_hslash.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.animation_model_hslash.frame
execute at @s run function animated_java:blueprint/animations/animation_model_hslash/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.animation_model_hslash.frame 1