# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,1f,0f,-1.0607f,1.0607f,0f,2.625f,-1.0607f,-1.0607f,0f,2.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_capsule_l2r0_125) {transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,2.4375f,0f,0f,-1.3333f,2.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hand) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2f,0f,0f,-1f,1.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm4) {transformation: [-1.0417f,0f,0f,0f,0f,1.0417f,0f,2f,0f,0f,-1.0417f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_3) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_2) {transformation: [-1.1667f,0f,0f,0f,0f,1.1667f,0f,0.5f,0f,0f,-1.1667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cap_locator_1":{"px":-2.5258340232414154e-16,"py":2.4375,"pz":2.0625,"ry":0,"rx":-90}}}