# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:blueprint rig_hash set value '5423f58417ce0d93ae4f9bf58716f7f87d08b5e35b7a2a616a6c11334cbc62b0'
scoreboard objectives add aj.animation_model_stand.frame dummy
scoreboard objectives add aj.animation_model_vslash.frame dummy
scoreboard objectives add aj.animation_model_hslash.frame dummy
scoreboard objectives add aj.animation_model_slash.frame dummy
scoreboard objectives add aj.animation_model_stab.frame dummy