# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:blueprint/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.blueprint.node.base] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.item_display] run data merge entity @s { transformation: [0f,0f,1f,0f,-1.0607f,1.0607f,0f,2.625f,-1.0607f,-1.0607f,0f,2.0625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.capsule_l2r0_125] run data merge entity @s { transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,2.4375f,0f,0f,-1.3333f,2.0625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.sword] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.hand] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2f,0f,0f,-1f,1.875f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.arm4] run data merge entity @s { transformation: [-1.0417f,0f,0f,0f,0f,1.0417f,0f,2f,0f,0f,-1.0417f,0.375f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.arm_3] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.arm_2] run data merge entity @s { transformation: [-1.1667f,0f,0f,0f,0f,1.1667f,0f,0.5f,0f,0f,-1.1667f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.arm_1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.blueprint.node.robotic_arm] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }