# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.base] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_base set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.item_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.capsule_l2r0_125] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_capsule_l2r0_125 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.hand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.arm4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.arm_3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.arm_2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.arm_1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_1 set from storage animated_java:gu out