# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add collision_check_capsule
data modify entity @s data merge value {param:{lenght:2f,radius:0.125f,locator:"cap_locator_1"}}