# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '5423f58417ce0d93ae4f9bf58716f7f87d08b5e35b7a2a616a6c11334cbc62b0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack