# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.blueprint.animation.animation_model_stand.playing
tag @s remove aj.blueprint.animation.animation_model_vslash.playing
tag @s remove aj.blueprint.animation.animation_model_hslash.playing
tag @s remove aj.blueprint.animation.animation_model_slash.playing
tag @s remove aj.blueprint.animation.animation_model_stab.playing